// Mock data for the AutoDownload prototype

export const currentUser = {
  id: 1,
  name: "Éder Casagranda",
  email: "eder.casagranda@email.com",
  initials: "EC",
  createdAt: "2026-04-18",
};

export const operadoras = [
  { id: 1, name: "CEEE Equatorial", type: "Energia", icon: "⚡" },
  { id: 2, name: "CORSAN", type: "Água", icon: "💧" },
  { id: 3, name: "Vero Internet", type: "Internet", icon: "📡" },
  { id: 4, name: "RMS Telecom", type: "Internet", icon: "RMS" },
];

export const contas = [
  {
    id: 1,
    operadoraId: 1,
    operadora: "CEEE Equatorial",
    tipo: "Energia",
    icon: "⚡",
    loginPortal: "eder.casagranda@email.com",
    unidadeConsumidora: "UC-4821903",
    status: "ativa",
    ultimaExecucao: "2026-05-23",
    proximaExecucao: "2026-05-28",
  },
  {
    id: 2,
    operadoraId: 2,
    operadora: "CORSAN",
    tipo: "Água",
    icon: "💧",
    loginPortal: "eder_corsan",
    unidadeConsumidora: "MAT-77210",
    status: "ativa",
    ultimaExecucao: "2026-05-23",
    proximaExecucao: "2026-05-28",
  },
];

export const boletos = [
  {
    id: 1,
    contaId: 1,
    operadora: "CEEE Equatorial",
    tipo: "Energia",
    icon: "⚡",
    referencia: "Maio 2026",
    vencimento: "2026-06-10",
    valor: 187.42,
    arquivo: "ceee_2026_05.pdf",
    baixadoEm: "2026-05-23T09:00:00",
    status: "disponivel",
  },
  {
    id: 2,
    contaId: 2,
    operadora: "CORSAN",
    tipo: "Água",
    icon: "💧",
    referencia: "Maio 2026",
    vencimento: "2026-06-15",
    valor: 94.18,
    arquivo: "corsan_2026_05.pdf",
    baixadoEm: "2026-05-23T09:02:00",
    status: "disponivel",
  },
  {
    id: 3,
    contaId: 1,
    operadora: "CEEE Equatorial",
    tipo: "Energia",
    icon: "⚡",
    referencia: "Abril 2026",
    vencimento: "2026-05-10",
    valor: 203.55,
    arquivo: "ceee_2026_04.pdf",
    baixadoEm: "2026-04-23T09:00:00",
    status: "disponivel",
  },
  {
    id: 4,
    contaId: 2,
    operadora: "CORSAN",
    tipo: "Água",
    icon: "💧",
    referencia: "Abril 2026",
    vencimento: "2026-05-15",
    valor: 88.3,
    arquivo: "corsan_2026_04.pdf",
    baixadoEm: "2026-04-23T09:02:00",
    status: "disponivel",
  },
];

export const historico = [
  {
    id: 1,
    contaId: 1,
    operadora: "CEEE Equatorial",
    tipo: "Energia",
    dataExecucao: "2026-05-23T09:00:00",
    status: "sucesso",
    mensagem: "Boleto de Maio/2026 baixado com sucesso.",
    arquivo: "ceee_2026_05.pdf",
    duracao: "12s",
  },
  {
    id: 2,
    contaId: 2,
    operadora: "CORSAN",
    tipo: "Água",
    dataExecucao: "2026-05-23T09:02:00",
    status: "sucesso",
    mensagem: "Boleto de Maio/2026 baixado com sucesso.",
    arquivo: "corsan_2026_05.pdf",
    duracao: "8s",
  },
  {
    id: 3,
    contaId: 1,
    operadora: "CEEE Equatorial",
    tipo: "Energia",
    dataExecucao: "2026-05-18T09:00:00",
    status: "falha",
    mensagem: "Timeout ao carregar portal. Tentativa será repetida.",
    arquivo: null,
    duracao: "30s",
  },
  {
    id: 4,
    contaId: 1,
    operadora: "CEEE Equatorial",
    tipo: "Energia",
    dataExecucao: "2026-04-23T09:00:00",
    status: "sucesso",
    mensagem: "Boleto de Abril/2026 baixado com sucesso.",
    arquivo: "ceee_2026_04.pdf",
    duracao: "11s",
  },
  {
    id: 5,
    contaId: 2,
    operadora: "CORSAN",
    tipo: "Água",
    dataExecucao: "2026-04-23T09:02:00",
    status: "sucesso",
    mensagem: "Boleto de Abril/2026 baixado com sucesso.",
    arquivo: "corsan_2026_04.pdf",
    duracao: "7s",
  },
];

export const notificacoes = [
  {
    id: 1,
    texto: "Boleto CEEE Equatorial (Maio 2026) baixado com sucesso.",
    data: "2026-05-23T09:00:00",
    lida: false,
  },
  {
    id: 2,
    texto: "Boleto CORSAN (Maio 2026) baixado com sucesso.",
    data: "2026-05-23T09:02:00",
    lida: false,
  },
  {
    id: 3,
    texto: "Falha ao acessar portal CEEE Equatorial. Nova tentativa agendada.",
    data: "2026-05-18T09:00:00",
    lida: true,
  },
];
